export const ENDPOINTS = {
  AUTH: {
    PRE_REGISTER: "/auth/pre-register/",
    ELIGIBILITY: "/auth/eligibility/",
    SEND_OTP: "/auth/send-otp/",
    VERIFY_OTP: "/auth/verify-otp/",
    REGISTER_COMPLETE: "/auth/register/",
    LOGIN: "/auth/login/",
    VERIFY_2FA: "/auth/2fa/verify/",
    LOGOUT: "/auth/logout/",
    PROFILE: "/auth/profile/",
    PROFILE_BY_USERNAME: (username: string) => `/auth/profile/${username}/`,
    CHANGE_PASSWORD: "/auth/change-password/",
    FORGOT_PASSWORD: "/auth/forgot-password/",
    RESET_PASSWORD: "/auth/reset-password/",
    ENABLE_2FA: "/auth/2fa/enable/",
    DISABLE_2FA: "/auth/2fa/disable/",
    BADGES: "/auth/badges/",
    DEACTIVATE: "/auth/deactivate/",
    CHANGE_USERNAME: "/auth/change-username/",
    CHANGE_USERNAME_OTP: "/auth/change-username/otp/",
  },
  KYC: {
    STATUS: "/kyc/status/",
    SEND_PHONE_OTP: "/kyc/phone/send-otp/",
    VERIFY_PHONE_OTP: "/kyc/phone/verify-otp/",
  },
  POSTS: {
    LIST: "/dots/",
    CREATE: "/dots/",
    DETAIL: (id: string) => `/dots/${id}/`,
    DELETE: (id: string) => `/dots/${id}/`,
    LIKE: (id: string) => `/dots/${id}/like/`,
    BOOKMARK: (id: string) => `/dots/${id}/bookmark/`,
    REPOST: (id: string) => `/dots/${id}/repost/`,
    REPORT: (id: string) => `/dots/${id}/report/`,
    REPLIES: (id: string) => `/dots/${id}/replies/`,
    DRAFTS: "/dots/my/drafts/",
    DRAFT_DETAIL: (id: string) => `/dots/my/drafts/${id}/`,
  },
  FEED: {
    FOR_YOU: "/feed/suggestions/timeline/",
    FOLLOWING: "/feed/following/",
  },
  BOOKMARKS: {
    LIST: "/bookmarks/",
  },
  USERS: {
    FOLLOW: (username: string) => `/users/${username}/follow/`,
    UNFOLLOW: (username: string) => `/users/${username}/unfollow/`,
    BLOCK: (username: string) => `/users/${username}/block/`,
    UNBLOCK: (username: string) => `/users/${username}/unblock/`,
    MUTE: (username: string) => `/users/${username}/mute/`,
    UNMUTE: (username: string) => `/users/${username}/unmute/`,
    FOLLOWERS: (username: string) => `/users/${username}/followers/`,
    FOLLOWING: (username: string) => `/users/${username}/following/`,
    RELATIONSHIP: (username: string) => `/users/${username}/relationship_status/`,
    CANCEL_FOLLOW_REQUEST: (username: string) => `/users/${username}/cancel-follow-request/`,
    ACCEPT_FOLLOW_REQUEST: (username: string) => `/users/${username}/accept-follow-request/`,
    PROFILE_DOTS: (username: string) => `/users/${username}/dots/`,
    PROFILE_REPLIES: (username: string) => `/users/${username}/replies/`,
    PROFILE_MEDIA: (username: string) => `/users/${username}/media/`,
    PROFILE_LIKES: (username: string) => `/users/${username}/likes/`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications/",
    MARK_READ: (id: string) => `/notifications/${id}/read/`,
    MARK_ALL_READ: "/notifications/mark-all-read/",
    PREFERENCES: "/notifications/preferences/",
    ACCEPT_FOLLOW: (id: string) => `/notifications/${id}/accept-follow/`,
    REJECT_FOLLOW: (id: string) => `/notifications/${id}/reject-follow/`,
  },
  MEDIA: {
    PRESIGN: "/media/presign/",
    CONFIRM: (id: string) => `/media/${id}/confirm/`,
  },
  REWARD: {
    STARS_BALANCE: "/reward/stars-balance/",
    DEFAULT_STARS: "/reward/default-stars/",
    STARS_SETTINGS: (id: string) => `/reward/stars-settings/${id}/`,
    DONATE_POST: "/reward/donate/post/",
    DONATE_USER: "/reward/donate/user/",
    TRANSACTIONS: "/reward/transactions/",
  },
  WALLET: {
    LIST: "/wallet/",
    LINK: "/wallet/link/",
    TOGGLE_DEFAULT: (id: string) => `/wallet/${id}/default/`,
  },
  BLOCKCHAIN: {
    MINT_ESTIMATE: "/blockchain/mint/estimate/",
    MINT_PREPARE: "/blockchain/mint/prepare/",
    MINT_SUBMIT: "/blockchain/mint/submit/",
    SWAP_STAR_TO_DOTO: "/blockchain/swap/star-to-doto/",
    HISTORY: "/blockchain/history/",
    MINT_HISTORY: "/blockchain/mint/history/",
  },
  CHAT: {
    CONVERSATIONS: "/conversations/",
    CONVERSATION_DETAIL: (id: string) => `/conversations/${id}/`,
    MESSAGES: (id: string) => `/conversations/${id}/messages/`,
    MESSAGE_DETAIL: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/`,
    PIN_MESSAGE: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/pin/`,
    PINNED_MESSAGES: (id: string) => `/conversations/${id}/pinned-messages/`,
    MEMBERS: (id: string) => `/conversations/${id}/members/`,
  },
} as const;
