export const ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  PROFILE: (username: string) => `/profile/${username}`,
  POST: (username: string, postId: string) => `/post/${username}/status/${postId}`,
  EXPLORE: "/explore",
  SEARCH: "/search",
  NOTIFICATIONS: (tab?: string) => tab ? `/notifications/${tab}` : "/notifications",
  BOOKMARKS: "/bookmarks",
  CHAT: "/chat",
  WALLET: "/wallet",
  NFT: "/nft",
  CONVERT: "/convert",
  SETTINGS: "/settings",
  SETTINGS_PROFILE: "/settings/profile",
  SETTINGS_ACCOUNT: "/settings/account",
  SETTINGS_SECURITY: "/settings/security",
  SETTINGS_NOTIFICATIONS: "/settings/notifications",
  SETTINGS_PRIVACY: "/settings/privacy",
} as const;
